apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-sidecar-injector-service
  namespace: {{ .Release.Namespace }}
spec:
  secretName: vault-policy-webhook-tls
  {{ if .Values.spec.webhookCertificate }}
  {{ if .Values.spec.webhookCertificate.duration }}
  duration: {{ .Values.spec.webhookCertificate.duration }}
  {{ end }}
  {{ if .Values.spec.webhookCertificate.renewBefore }}
  renewBefore: {{ .Values.spec.webhookCertificate.renewBefore }} 
  {{ end }}
  {{ end }}
  issuerRef:
    name: vault-issuer
  dnsNames:
  - "vault-access-admission-webhook"
  - "vault-access-admission-webhook.vault-access-definitions"
  - "vault-access-admission-webhook.vault-access-definitions.svc"