apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-sidecar-injector-service
  namespace: {{ .Release.Namespace }}
spec:
  secretName: vault-policy-webhook-tls
  duration: 30m
  renewBefore: 20m 
  issuerRef:
    name: vault-issuer
  dnsNames:
  - "vault-access-admission-webhook"
  - "vault-access-admission-webhook.vault-access-definitions"
  - "vault-access-admission-webhook.vault-access-definitions.svc"