apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-access-admission-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-access-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-access-admission-webhook
  template:
    metadata:
      labels:
        app: vault-access-admission-webhook
    spec:
      containers:
        - name: vault-access-admission-webhook
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: Vault__Token
              valueFrom:
                secretKeyRef:
                  name: ms-secret-access-manager-auth-secret
                  key: token
            - name: Vault__Server
              value: {{ .Values.spec.vault.server }}
            - name: Vault__RoleName
              value: {{ .Values.spec.vault.roleName }}