apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-access-admission-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-access-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-access-admission-webhook
  template:
    metadata:
      labels:
        app: vault-access-admission-webhook
    spec:
      volumes:
        - name: tls-secrets
          secret:
            secretName: vault-policy-webhook-tls
        - name: pfx
          emptyDir: {}
      containers:
        - name: vault-access-admission-webhook
          image: {{ .Values.spec.image }}
          # imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-secrets
              mountPath: /var/lib/tls
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 443
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 443
            initialDelaySeconds: 60
            periodSeconds: 60
          env:
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: TlsCertPath
              value: /var/lib/tls/tls.crt
            - name: TlsKeyPath
              value: /var/lib/tls/tls.key
            - name: Vault__Token
              valueFrom:
                secretKeyRef:
                  name: ms-secret-access-manager-auth-secret
                  key: token
            - name: Vault__Server
              value: {{ .Values.spec.vault.server }}
            - name: Vault__RoleName
              value: {{ .Values.spec.vault.roleName }}
            - name: Vault__AuthMountPoint
              value: {{ .Values.spec.vault.authMountPath }}