apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    server: {{ .Values.spec.vault.server }}
    path: pki/sign/vault-policy-webhook
    auth:
      kubernetes:
        mountPath: /v1/auth/{{ .Values.spec.vault.authMountPath }}
        role: webhook-issuer
        secretRef:
          name: webhook-issuer-auth-secret
          key: token