# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ms-secret-access-manager
#   namespace: {{ .Release.Namespace }}

# --- 

apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-issuer
  namespace: {{ .Release.Namespace }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: webhook-issuer-auth-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: webhook-issuer
type: kubernetes.io/service-account-token