apiVersion: v1
kind: Service
metadata:
  name: vault-access-admission-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-access-admission-webhook
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: vault-access-admission-webhook