apiVersion: v1
kind: Secret
metadata:
  name: ms-secret-access-manager-auth-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: ms-secret-access-manager
type: kubernetes.io/service-account-token