installCRDs: true
spec:  
  image: canpolatoral/vault-admission-webhook:0.2
  webhookPath: "/validationwebhook/validate"
  vault:
    token: ""
    server: http://host.minikube.internal:8200  
    roleName: "ms-secret-access-manager"
  accessDefinitions:
    - serviceAccountName: TestServiceAccount1
      serviceAccountNamespace: TestServiceAccountNamespace1
      secretPath: vk/TestSecretPath1Test
    - serviceAccountName: TestServiceAccount2
      serviceAccountNamespace: TestServiceAccountNamespace2
      secretPath: vk/TestSecretPath2