installCRDs: true
spec:  
  image: canpolatoral/vault-admission-webhook:0.7
  webhookPath: "/validationwebhook/validate"
  vault:
    server: http://host.minikube.internal:8200  
    roleName: "ms-secret-access-manager"
    authMountPath: "" # environment and cluster based
  accessDefinitions: # environment and cluster based
    # - serviceAccountName: TestServiceAccount1
    #   serviceAccountNamespace: TestServiceAccountNamespace1
    #   secretPath: vk/TestSecretPath11
    # - serviceAccountName: TestServiceAccount2
    #   serviceAccountNamespace: TestServiceAccountNamespace2
    #   secretPath: vk/TestSecretPath2