installCRDs: true
spec:  
  image: canpolatoral/vault-admission-webhook:0.15
  # webhookPath: "/validationwebhook/validate"
  webhookUrl: "https://localhost:7155/validationwebhook/validate"
  vault:
    server: http://host.minikube.internal:8200  
    roleName: "ms-secret-access-manager"
    authMountPath: "" # environment and cluster based
  webhookCertificate: 
    duration: 2160h # 90d
    renewBefore: 360h # 15d
  #   duration: 60m
  #   renewBefore: 5m